project_name: DMTL_hyperparam_cifar_hetro_30

# FL configuration
num_clients: 30
n_rounds: 200 
m: 0.50
local_epochs: 5 
agg: mtl

#DMTL params
lambda_: 0.03
alpha: 0.49
lambda_anchor: 0.1
momentum_anchor: 0.5

# FLearner arguments
client_selector: BaseClientSelector
client_cls: DMTL
loss_fn: CrossEntropyLoss
writer: WandbWriter


# save and log directories
root_dir: /scratch/project_2009050/
save_dir : models
res_dir: results
log_dir: logs
state_dir: aggregated_model_

# metrics
training_metrics: [accuracy_score]
test_metrics: [accuracy_score]

# Data configuration
data:
  data_dir: /scratch/project_2009050/
  modality: [Vision]
  batch_size: 32
  name: cifar10_hetro_30
  niid: false
  balance: false
  partitioner: DirPartitioner
  alpha: 0.1
  train_ratio: 0.75
  num_classes: 10
  classes: [plane, car, bird, cat, deer, dog, frog, horse, ship, truck]


# Model configuration
model:
  name: CIFAR10Model
  in_channels: 3
  img_size: 32
  hidden_dim: 512
  num_classes: 10
  grad_norm_clip: 1.0


# optimzer configuration
optimizer:
  name: SGD
  lr: 0.05
  weight_decay: 0.0